### ISSUE TITLE
[bug] Load of results from RVFWHMmodel is broken

### ISSUE THREAD

**Issue by Kamuish** [kima-org/kima#24]
Hi,

I am trying to load kima products using the following MWE

```

with chdir(selected_folder):
    with open(selected_folder / "kima_model_setup.txt") as to_read:
        for line in to_read:
            if "files" in line:
                input_files = line.split(":")[-1].split(",")[:-1]
                input_files = [i.strip() for i in input_files]
                break

    data = RVData(
        filenames=input_files,
        units="kms",
        skip=0,
        indicators=["fwhm", "s-fwhm", "cont", "s-cont", "bis", "s-bis"],
    )
    model = RVFWHMmodel(fix=False, npmax=2, data=data)

    res = kima.load_results(model, diagnostic=False)

```

It is failing with

```
Traceback (most recent call last):
  File "/home/amiguel/work/RV_analysis/EpsIndi/kima_runs/teste_joint.py", line 47, in <module>
    res = kima.load_results(model, diagnostic=False)
  File "/home/amiguel/work/RV_analysis/venv/lib64/python3.9/site-packages/kima/pykima/results.py", line 245, in load_results
    res = KimaResults(model_or_file, data,
  File "/home/amiguel/work/RV_analysis/venv/lib64/python3.9/site-packages/kima/pykima/results.py", line 602, in __init__
    self._read_GP()
  File "/home/amiguel/work/RV_analysis/venv/lib64/python3.9/site-packages/kima/pykima/results.py", line 850, in _read_GP
    self.kernel = GPmodel.KernelType(int(self.setup['kima']['kernel']))
ValueError: invalid literal for int() with base 10: 'standard'

```

**Comment by j-faria** [comment]
Can you check if this is still causing an error with the current version on `main` (after commit 0e8e5dd)

**Comment by Kamuish** [comment]
The new version does not even run the RVFWHM model with the default configurations

```python
 model = RVFWHMmodel(
fix=fix,
        npmax=NPmax,
        data=data,
    )
model.enforce_stability = True
model.trend = True
model.degree = 1
kima.run(
    model,
    steps=n_steps,
    num_threads=30,
    new_level_interval=4000,
)
```

This fails with

```bash
(venv) ➜  EpsIndi python kima_runs/apply_kima.py
# Seeding random number generators. First seed = 1736503611.
# Generating 30 particles from the prior...Traceback (most recent call last):
  File "/home/amiguel/RV_analysis/EpsIndi/kima_runs/apply_kima.py", line 98, in <module>
    run_kima(
    ~~~~~~~~^
        (results_path / "jointModel").as_posix(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        run_joint_model=True,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/amiguel/RV_analysis/EpsIndi/kima_runs/apply_kima.py", line 84, in run_kima
    kima.run(
    ~~~~~~~~^
        model,
        ^^^^^^
    ...<2 lines>...
        new_level_interval=4000,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
ValueError: LogUniform distribution must have lower < upper limits
```

I can't seem to find which prior is setting the LogUniform distribution with the incorrect parameters, as a breakpoint() before the *kima.run* shows all priors to be None

**Comment by j-faria** [comment]
> ValueError: LogUniform distribution must have lower < upper limits

This is probably coming from the default prior for `eta1_fwhm`, which uses the span of the observed FWHM. Can you check if the FWHM is in the right units?

**Comment by JeanCostes** [comment]
Hi, 

I've got a slightly similar issue regarding the kima.load_results() for the FWHMRHKmodel 
(the RVmodel and the GPmodel are working fine though).
```

data = RVData(kima_file, indicators=['fwhm', 'err_fwhm', 'rhk', 'err_rhk'], units='ms')
model_3 = RVFWHMRHKmodel(fix=True, npmax=npmax, data=data)
kima.run(model_3, steps=k_steps, num_threads=num_threads, num_particles=num_particles, print_thin=int(k_steps/10))
```

And failing:

```
ValueError                                Traceback (most recent call last)
Cell In[68], line 1
----> 1 res3 = kima.load_results(model_3)

File ~/anaconda3/lib/python3.11/site-packages/kima/pykima/results.py:245, in load_results(model_or_file, data, diagnostic, verbose, moreSamples)
    243 if hasattr(model_or_file, 'directory') and model_or_file.directory != '':
    244     with chdir(model_or_file.directory):
--> 245         res = KimaResults(model_or_file, data,
    246                           diagnostic=diagnostic, verbose=verbose)
    247 else:
    248     res = KimaResults(model_or_file, data,
    249                       diagnostic=diagnostic, verbose=verbose)

File ~/anaconda3/lib/python3.11/site-packages/kima/pykima/results.py:617, in KimaResults.__init__(self, model, data, diagnostic, moreSamples, save_plots, return_figs, verbose)
    614 self._read_actind_correlations()
    616 # find GP in the compiled model
--> 617 self._read_GP()
    619 # # find MA in the compiled model
    620 # self._read_MA()
    621 
    622 # find KO in the compiled model
    623 self.KO = model.known_object

File ~/anaconda3/lib/python3.11/site-packages/kima/pykima/results.py:874, in KimaResults._read_GP(self)
    872 self.has_gp = True
    873 try:
--> 874     self.kernel = GP.KernelType(int(self.setup['kima']['kernel']))
    875 except KeyError:
    876     self.kernel = GP.KernelType(0)

ValueError: invalid literal for int() with base 10: 'standard'
```

Any idea what is causing this issue?

**Comment by j-faria** [comment]
I think these issues are fixed now.
@JeanCostes, could you check if your example with the `RVFWHMRHKmodel` works now?

**Comment by JeanCostes** [comment]
Hi,
I've tested the latest version, and despite this issue:

```
File ~/anaconda3/lib/python3.11/site-packages/kima/pykima/results.py:856, in KimaResults._read_GP(self)
    854 self.has_gp = True
    855 try:
--> 856     self.kernel = GP.KernelType(int(self.setup['kima']['kernel']))
    857 except KeyError:
    858     self.kernel = GP.KernelType(0)
ValueError: invalid literal for int() with base 10: 'standard'
```

which I simply ignored by commenting all lines above using only:
`self.kernel = GP.KernelType(0)`

The rest of the code seems to be running smoothly without any other crashes. 
Thank you for your quick reply :)

**Comment by j-faria** [comment]
Thank you, happy it's working better.

I'm assuming you didn't re-run the model and tried instead to load previous results? That's probably the issue with the kernel, which was written in the `kima_model_setup.txt` file as 'standard' in a previous version, but should now be correct. So, I imagine if you ran the model this would be fixed.
