### ISSUE TITLE
[bug] kima-showresults fails when using the "phase" option

### ISSUE THREAD

**Issue by Kamuish** [kima-org/kima#38]
When launching the kima-showresults I get the following error:

```bash
kima-showresults rv planets
  Traceback (most recent call last):
  File "/home/amiguel/phd/tools/kima/kima_env/bin/kima-showresults", line 33, in <module>
      sys.exit(load_entry_point('pykima==4.0.4', 'console_scripts', 'kima-showresults')())
    File "/home/amiguel/phd/tools/kima/kima_env/lib/python3.9/site-packages/pykima-4.0.4-py3.9.egg/pykima/showresults.py", line 252, in showresults
    res.make_plots(list(set(plots)), save_plots=args.save_plots)
  File "/home/amiguel/phd/tools/kima/kima_env/lib/python3.9/site-packages/pykima-4.0.4-py3.9.egg/pykima/results.py", line 893, in make_plots
    display.make_plots(self, options, save_plots)
  File "/home/amiguel/phd/tools/kima/kima_env/lib/python3.9/site-packages/pykima-4.0.4-py3.9.egg/pykima/display.py", line 69, in make_plots
    exec(methods)
  File "<string>", line 1, in <module>
  File "/home/amiguel/phd/tools/kima/kima_env/lib/python3.9/site-packages/pykima-4.0.4-py3.9.egg/pykima/results.py", line 890, in phase_plot
    return display.phase_plot(self, sample, highlight)
  File "/home/amiguel/phd/tools/kima/kima_env/lib/python3.9/site-packages/pykima-4.0.4-py3.9.egg/pykima/display.py", line 912, in phase_plot
    fig.canvas.set_window_title('phase plot')
  AttributeError: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'

```

**Comment by Paul-Charpentier** [comment]
Hello

removing line 912 `fig.canvas.set_window_tiltle('phase plot')` in `display.py` worked for me as a temporary fix.

**Comment by j-faria** [comment]
This was happening in a (very) old version, so I'll just assume that it's fixed now and close the issue 🤞
