### ISSUE TITLE
kima.loads_results breaks with the RVFWHMmodel

### ISSUE THREAD

**Issue by Kamuish** [kima-org/kima#9]
```python
log(Z) = 60.72229023124929
Information = 56.073325494494256 nats.
Effective sample size = 9006.831737722428
Traceback (most recent call last):
  File "WG1Andre/plot_kima.py", line 21, in <module>
    res = kima.load_results(diagnostic=False)
  File "/data/work/amiguel/kima_target_analysis/WG1Andre/venv/lib/python3.8/site-packages/kima/pykima/results.py", line 196, in load_results
    res = KimaResults()
  File "/data/work/amiguel/kima_target_analysis/WG1Andre/venv/lib/python3.8/site-packages/kima/pykima/results.py", line 345, in __init__
    self._read_GP()
  File "/data/work/amiguel/kima_target_analysis/WG1Andre/venv/lib/python3.8/site-packages/kima/pykima/results.py", line 939, in _read_GP
    self.GP1 = GP(kernels[self.GPkernel], t, e, white_noise=0.0)
AttributeError: 'KimaResults' object has no attribute 'GPkernel'

```

**Comment by j-faria** [comment]
Is this still true if you do ```res = kima.load_results(model, diagnostic=False)``` ?

**Comment by Kamuish** [comment]
Closing the issue as the loading from the RVFWHMmodel is now fixed
